config/routes.rb
Rails.application.routes.draw do
  


  get "search" => "search#create", as: :search

  
  #este el el resource del nuevo controlador que hice
  resources :pgallery

  #esto no jala :v creo
  get 'profes' => 'pgallery#index', as: :profes
 # get 'profeperfil' => 'pgallery#show', as: :profeperfil 
  # get 'profesors/index'
  


  

      
  
  root 'home#index'
  #resources :profesors
  #los devise de alumnos y profesores
  devise_for :alumnos, path: 'alumnos',controllers: { sessions: 'alumnos/sessions' }
  devise_for :profesors, path: 'profesors',controllers: {sessions: 'profesors/sessions' }



  resources :clases
  resources :alumno_actividads
  resources :actividad_instructors
  resources :instructors
  resources :actividad_extras
  resources :materia
  resources :clase_alumnos
  #no se de donde vergas salio 'motivacion'
  resources :clasesmotivacion

  #perfil de alumnos
  get "perfil" => "alumnos#perfil", as: :perfil


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad_extra.rb
class ActividadExtra < ApplicationRecord
end

app/models/actividad_instructor.rb
class ActividadInstructor < ApplicationRecord
  belongs_to :actividadExtra
  belongs_to :instructor
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   mount_uploader :image, ImageUploader      
end

app/models/alumno_actividad.rb
class AlumnoActividad < ApplicationRecord
  belongs_to :alumno
  belongs_to :actividadinstructor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clase.rb
class Clase < ApplicationRecord
  belongs_to :materium
  belongs_to :profesor
end

app/models/clase_alumno.rb
class ClaseAlumno < ApplicationRecord
  belongs_to :alumno
  belongs_to :clase
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/materium.rb
class Materium < ApplicationRecord
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader        
end

app/controllers/clases_controller.rb
class ClasesController < ApplicationController
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.all

    @profesor_actual = ""
    @materia_actual = ""
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'Clase was successfully created.' }
        format.json { render :show, status: :created, location: @clase }
      else
        format.html { render :new }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'Clase was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase }
      else
        format.html { render :edit }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'Clase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:clave, :materium_id, :profesor_id, :indice, :horario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def create
  	palabra = "%#{params[:keyword]}%"

  	@profesors = Profesor.where("nombre LIKE ? OR ap_pat LIKE ? OR ap_mat LIKE ?",palabra,palabra,palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @profesors}
      format.js
    end
  end

   def searchmateria
  	palabra = "%#{params[:keywordm]}%"

  	@materia = Materium.where("nombre LIKE ? ",palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @materia}
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clase_alumnos_helper.rb
module ClaseAlumnosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/pgallery_helper.rb
module PgalleryHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/clases/_form.html.erb
<%= form_with(model: clase, local: true) do |form| %>
  <% if clase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clase.errors.count, "error") %> prohibited this clase from being saved:</h2>

      <ul>
      <% clase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :clave %>
    <%= form.text_field :clave, id: :clase_clave %>
  </div>

  <div class="field">
    <%= form.label :materium_id %>
    <%= form.text_field :materium_id, id: :clase_materium_id %>
  </div>

  <div class="field">
    <%= form.label :profesor_id %>
    <%= form.text_field :profesor_id, id: :clase_profesor_id %>
  </div>

  <div class="field">
    <%= form.label :indice %>
    <%= form.number_field :indice, id: :clase_indice %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_area :horario, id: :clase_horario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clases/edit.html.erb
<h1>Editing Clase</h1>

<%= render 'form', clase: @clase %>

<%= link_to 'Show', @clase %> |
<%= link_to 'Back', clases_path %>

app/views/clases/index.html.erb
<p id="notice"><%= notice %></p>

<div class="titulo">
  CLASES
</div>

 <div id="results" class="container" style="left: 90px; width: 250px">
   <div class="row" border-radius="55px" style="padding-bottom: 15px">
<div class="contenedor">
    <% @clases.each do |clase| %>
        <% @materia_actual = Materium.find_by(id: clase.materium)%>
        <% @profesor_actual = Profesor.find_by(id: clase.profesor)%>

       <div class="itemx">
              <% if clase.indice.to_i > 50%>
                <%filtro = "hovereffect" %>
              <% else%>
                <%filtro = "hovereffect4" %>
              <% end%>
              <div class="<%= filtro%>">
                  <%=image_tag("materia.png", height: '230', width: '200')%>
                <div class="overlay">
                     <h2> <%= link_to @materia_actual.nombre, clase %> <%= clase.horario %></h2>
                    <p>
                      <a href="#"><%= clase.indice %></a>
                    </p>
                </div>
              </div>
            </div>

    <% end %>
  </div>
    <br>

    <%= link_to 'New Clase', new_clase_path %>

     </div>
            </div>

app/views/clases/new.html.erb
<h1>New Clase</h1>

<%= render 'form', clase: @clase %>

<%= link_to 'Back', clases_path %>

app/views/clases/show.html.erb
<p id="notice"><%= notice %></p>
<% @materia_actual = Materium.find_by(id: @clase.materium)%>
<% @profesor_actual = Profesor.find_by(id: @clase.profesor)%>

<center>
<div class="info_clase_alumnos">

  <p>
    <strong>Profesor:</strong><br>
    <%= @profesor_actual.titulo%>. <%= @profesor_actual.nombre%> <%= @profesor_actual.ap_pat%> <%= @profesor_actual.ap_mat%>
  </p>

  <p>
    <strong>Materia:</strong><br>
    <%= @materia_actual.nombre %>
  </p>

  <p>
    <strong>Horario:</strong><br>
    <%= @clase.horario %>
  </p>
</div>
  </center>
<br><br>

<center>
  <% param = @clase.id%>
  <strong><%= link_to 'Deja tu comentario!', new_clase_alumno_path(:clase_comment => param) %></strong>

  <% p = ClaseAlumno.where(clase_id: @clase.id)%>

  <% p.each do |comment|%>
      <div class="bueno">
        <h1><%= comment.comentario%></h1>
      </div>
<!--
    <%al = Alumno.find_by(id: comment.alumno_id)%>
  	<h1><%= al.nombre%></h1>
-->
  <%end%>
</center>

app/views/home/index.html.erb
<html>
<body>


 
 <div class="grid-block" style="background-image: url('https://png.pngtree.com/thumb_back/fw800/back_pic/00/01/38/1156014b2176aaa.jpg'); width: 100%; height: 50vh; "> </div>
<%if alumno_signed_in? or profesor_signed_in?%>
<%else%>
<a><%= link_to "Inicia como alumno", new_alumno_session_path, class:'boton azul'%></a>
  <a><%= link_to "Inicia como profesor", new_profesor_session_path, class:'boton rojo'%></a>
<%end%>
 
</body>

<style type="text/css">
	
	.boton{
            text-align:center;
            text-decoration: none;
      font-family: 'Helvetica Neue', Helvetica, sans-serif;
      display:inline-block;
            color: #FFF;
            background: #7F8C8D;
            padding: 15px 40px;
            white-space: nowrap;
            margin: 10px 5px;
            -webkit-transition: all 0.2s ease-in-out;
            -ms-transition: all 0.2s ease-in-out;
            -moz-transition: all 0.2s ease-in-out;
            -o-transition: all 0.2s ease-in-out;
            transition: all 0.2s ease-in-out;
}
      
.azul{
  background: #3498DB;
  box-shadow: 0px 5px 0px 0px #2980B9;
}

.azul:hover{
  background: #39a0e5;
}

.azul:active{
  box-shadow: 0px 2px 0px 0px #2980B9;
}

.verde{
  background: #2ECC71;
  box-shadow: 0px 5px 0px 0px #27AE60;
}

.verde:hover{
  background: #32db78;
}

.verde:active{
  box-shadow: 0px 2px 0px 0px #27AE60;
}

.rojo{
  background: #E74C3C;
  box-shadow: 0px 5px 0px 0px #C0392B;
}

.rojo:hover{
  background: #ff5242;
}

.rojo:active{
  box-shadow: 0px 2px 0px 0px #C0392B;
}
</style>
</html>