config/routes.rb
Rails.application.routes.draw do
  


  get "search" => "search#create", as: :search

  
  #este el el resource del nuevo controlador que hice
  resources :pgallery

  #esto no jala :v creo
  get 'profes' => 'pgallery#index', as: :profes
 # get 'profeperfil' => 'pgallery#show', as: :profeperfil 
  # get 'profesors/index'
  


  

      
  
  root 'home#index'
  #resources :profesors
  #los devise de alumnos y profesores
  devise_for :alumnos, path: 'alumnos',controllers: { sessions: 'alumnos/sessions' }
  devise_for :profesors, path: 'profesors',controllers: {sessions: 'profesors/sessions' }



  resources :clases
  resources :alumno_actividads
  resources :actividad_instructors
  resources :instructors
  resources :actividad_extras
  resources :materia
  resources :clase_alumnos
  #no se de donde vergas salio 'motivacion'
  resources :clasesmotivacion

  #perfil de alumnos
  get "perfil" => "alumnos#perfil", as: :perfil


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad_extra.rb
class ActividadExtra < ApplicationRecord
end

app/models/actividad_instructor.rb
class ActividadInstructor < ApplicationRecord
  belongs_to :actividadExtra
  belongs_to :instructor
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   mount_uploader :image, ImageUploader      
end

app/models/alumno_actividad.rb
class AlumnoActividad < ApplicationRecord
  belongs_to :alumno
  belongs_to :actividadinstructor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clase.rb
class Clase < ApplicationRecord
  belongs_to :materium
  belongs_to :profesor
end

app/models/clase_alumno.rb
class ClaseAlumno < ApplicationRecord
  belongs_to :alumno
  belongs_to :clase
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/materium.rb
class Materium < ApplicationRecord
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader        
end

app/controllers/clases_controller.rb
class ClasesController < ApplicationController
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.all

    @profesor_actual = ""
    @materia_actual = ""
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'Clase was successfully created.' }
        format.json { render :show, status: :created, location: @clase }
      else
        format.html { render :new }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'Clase was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase }
      else
        format.html { render :edit }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'Clase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:clave, :materium_id, :profesor_id, :indice, :horario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:ap_pat, :ap_mat, :nombre)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def create
  	palabra = "%#{params[:keyword]}%"

  	@profesors = Profesor.where("nombre LIKE ? OR ap_pat LIKE ? OR ap_mat LIKE ?",palabra,palabra,palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @profesors}
      format.js
    end
  end

   def searchmateria
  	palabra = "%#{params[:keywordm]}%"

  	@materia = Materium.where("nombre LIKE ? ",palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @materia}
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clase_alumnos_helper.rb
module ClaseAlumnosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/pgallery_helper.rb
module PgalleryHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ap_pat %>
    <%= form.text_field :ap_pat, id: :instructor_ap_pat %>
  </div>

  <div class="field">
    <%= form.label :ap_mat %>
    <%= form.text_field :ap_mat, id: :instructor_ap_mat %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :instructor_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Ap pat</th>
      <th>Ap mat</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.ap_pat %></td>
        <td><%= instructor.ap_mat %></td>
        <td><%= instructor.nombre %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ap pat:</strong>
  <%= @instructor.ap_pat %>
</p>

<p>
  <strong>Ap mat:</strong>
  <%= @instructor.ap_mat %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @instructor.nombre %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>