config/routes.rb
Rails.application.routes.draw do
  


  get "search" => "search#create", as: :search

  
  #este el el resource del nuevo controlador que hice
  resources :pgallery

  #esto no jala :v creo
  get 'profes' => 'pgallery#index', as: :profes
 # get 'profeperfil' => 'pgallery#show', as: :profeperfil 
  # get 'profesors/index'
  


  

      
  
  root 'home#index'
  #resources :profesors
  #los devise de alumnos y profesores
  devise_for :alumnos, path: 'alumnos',controllers: { sessions: 'alumnos/sessions' }
  devise_for :profesors, path: 'profesors',controllers: {sessions: 'profesors/sessions' }



  resources :clases
  resources :alumno_actividads
  resources :actividad_instructors
  resources :instructors
  resources :actividad_extras
  resources :materia
  resources :clase_alumnos
  #no se de donde vergas salio 'motivacion'
  resources :clasesmotivacion

  #perfil de alumnos
  get "perfil" => "alumnos#perfil", as: :perfil


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad_extra.rb
class ActividadExtra < ApplicationRecord
end

app/models/actividad_instructor.rb
class ActividadInstructor < ApplicationRecord
  belongs_to :actividadExtra
  belongs_to :instructor
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   mount_uploader :image, ImageUploader      
end

app/models/alumno_actividad.rb
class AlumnoActividad < ApplicationRecord
  belongs_to :alumno
  belongs_to :actividadinstructor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clase.rb
class Clase < ApplicationRecord
  belongs_to :materium
  belongs_to :profesor
end

app/models/clase_alumno.rb
class ClaseAlumno < ApplicationRecord
  belongs_to :alumno
  belongs_to :clase
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/materium.rb
class Materium < ApplicationRecord
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader        
end

app/controllers/clase_alumnos_controller.rb
class ClaseAlumnosController < ApplicationController
  before_action :set_clase_alumno, only: [:show, :edit, :update, :destroy]

  # GET /clase_alumnos
  # GET /clase_alumnos.json
  def index
    @clase_alumnos = ClaseAlumno.all
  end

  # GET /clase_alumnos/1
  # GET /clase_alumnos/1.json
  def show
  end

  # GET /clase_alumnos/new
  def new
    @clase_alumno = ClaseAlumno.new
    @id_guardar = params[:clase_comment]
  end

  # GET /clase_alumnos/1/edit
  def edit
  end

  # POST /clase_alumnos
  # POST /clase_alumnos.json
  def create
    @clase_alumno = ClaseAlumno.new(clase_alumno_params)

    respond_to do |format|
      if @clase_alumno.save
        format.html { redirect_to root_path, notice: 'Clase alumno was successfully created.' }
        format.json { render :show, status: :created, location: @clase_alumno }
      else
        format.html { render :new }
        format.json { render json: @clase_alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clase_alumnos/1
  # PATCH/PUT /clase_alumnos/1.json
  def update
    respond_to do |format|
      if @clase_alumno.update(clase_alumno_params)
        format.html { redirect_to @clase_alumno, notice: 'Clase alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase_alumno }
      else
        format.html { render :edit }
        format.json { render json: @clase_alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clase_alumnos/1
  # DELETE /clase_alumnos/1.json
  def destroy
    @clase_alumno.destroy
    respond_to do |format|
      format.html { redirect_to clase_alumnos_url, notice: 'Clase alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase_alumno
      @clase_alumno = ClaseAlumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_alumno_params
      params.require(:clase_alumno).permit(:alumno_id, :clase_id, :comentario, :calificacion)
    end
end

app/controllers/clases_controller.rb
class ClasesController < ApplicationController
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.all

    @profesor_actual = ""
    @materia_actual = ""
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'Clase was successfully created.' }
        format.json { render :show, status: :created, location: @clase }
      else
        format.html { render :new }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'Clase was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase }
      else
        format.html { render :edit }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'Clase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:clave, :materium_id, :profesor_id, :indice, :horario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def create
  	palabra = "%#{params[:keyword]}%"

  	@profesors = Profesor.where("nombre LIKE ? OR ap_pat LIKE ? OR ap_mat LIKE ?",palabra,palabra,palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @profesors}
      format.js
    end
  end

   def searchmateria
  	palabra = "%#{params[:keywordm]}%"

  	@materia = Materium.where("nombre LIKE ? ",palabra)
    
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: @materia}
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clase_alumnos_helper.rb
module ClaseAlumnosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/pgallery_helper.rb
module PgalleryHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/clase_alumnos/_form.html.erb
<%= form_with(model: clase_alumno, local: true) do |form| %>


  <% if clase_alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clase_alumno.errors.count, "error") %> prohibited this clase_alumno from being saved:</h2>

      <ul>
      <% clase_alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% p = current_alumno %>
  <div class="field">
    <% form.label :alumno_id %>
    <%= form.text_field :alumno_id, id: :clase_alumno_alumno_id , :value => p.id, :readonly => true%>
  </div>

  <div class="field">
    <% form.label :clase_id %>
    <%= form.text_field :clase_id, id: :clase_alumno_clase_id , :value => @id_guardar, :readonly => true%>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario, id: :clase_alumno_comentario %>
  </div>

  <div class="field">
    <%=form.select :calificacion, options_for_select([["Malo",1],["Regular",2],["Bueno",3]])%><br><br>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clase_alumnos/edit.html.erb
<h1>Editing Clase Alumno</h1>

<%= render 'form', clase_alumno: @clase_alumno %>

<%= link_to 'Show', @clase_alumno %> |
<%= link_to 'Back', clase_alumnos_path %>

app/views/clase_alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clase Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Alumno</th>
      <th>Clase</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clase_alumnos.each do |clase_alumno| %>
      <tr>
        <td><%= clase_alumno.alumno %></td>
        <td><%= clase_alumno.clase %></td>
        <td><%= clase_alumno.comentario %></td>
        <td><%= link_to 'Show', clase_alumno %></td>
        <td><%= link_to 'Edit', edit_clase_alumno_path(clase_alumno) %></td>
        <td><%= link_to 'Destroy', clase_alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clase Alumno', new_clase_alumno_path %>

app/views/clase_alumnos/new.html.erb
<center>
<br>
<div class="titulo">
  DEJA TU COMENTARIO!
</div>
<br>
<br>

<!--
<h1><%= @id_guardar %></h1>
-->
<%= render 'form', clase_alumno: @clase_alumno %>

<%= link_to 'Back', clase_alumnos_path %>

</center>

app/views/clase_alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alumno:</strong>
  <%= @clase_alumno.alumno %>
</p>

<p>
  <strong>Clase:</strong>
  <%= @clase_alumno.clase %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @clase_alumno.comentario %>
</p>

<%= link_to 'Edit', edit_clase_alumno_path(@clase_alumno) %> |
<%= link_to 'Back', clase_alumnos_path %>