config/routes.rb
Rails.application.routes.draw do
  


  get "search" => "search#create", as: :search

  
  #este el el resource del nuevo controlador que hice
  resources :pgallery

  #esto no jala :v creo
  get 'profes' => 'pgallery#index', as: :profes
 # get 'profeperfil' => 'pgallery#show', as: :profeperfil 
  # get 'profesors/index'
  


  

      
  
  root 'home#index'
  #resources :profesors
  #los devise de alumnos y profesores
  devise_for :alumnos, path: 'alumnos',controllers: { sessions: 'alumnos/sessions' }
  devise_for :profesors, path: 'profesors',controllers: {sessions: 'profesors/sessions' }



  resources :clases
  resources :alumno_actividads
  resources :actividad_instructors
  resources :instructors
  resources :actividad_extras
  resources :materia
  resources :clase_alumnos
  #no se de donde vergas salio 'motivacion'
  resources :clasesmotivacion

  #perfil de alumnos
  get "perfil" => "alumnos#perfil", as: :perfil


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad_extra.rb
class ActividadExtra < ApplicationRecord
end

app/models/actividad_instructor.rb
class ActividadInstructor < ApplicationRecord
  belongs_to :actividadExtra
  belongs_to :instructor
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   mount_uploader :image, ImageUploader      
end

app/models/alumno_actividad.rb
class AlumnoActividad < ApplicationRecord
  belongs_to :alumno
  belongs_to :actividadinstructor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clase.rb
class Clase < ApplicationRecord
  belongs_to :materium
  belongs_to :profesor
end

app/models/clase_alumno.rb
class ClaseAlumno < ApplicationRecord
  belongs_to :alumno
  belongs_to :clase
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/materium.rb
class Materium < ApplicationRecord
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader        
end

app/controllers/actividad_instructors_controller.rb
class ActividadInstructorsController < ApplicationController
  before_action :set_actividad_instructor, only: [:show, :edit, :update, :destroy]

  # GET /actividad_instructors
  # GET /actividad_instructors.json
  def index
    @actividad_instructors = ActividadInstructor.all
  end

  # GET /actividad_instructors/1
  # GET /actividad_instructors/1.json
  def show
  end

  # GET /actividad_instructors/new
  def new
    @actividad_instructor = ActividadInstructor.new
  end

  # GET /actividad_instructors/1/edit
  def edit
  end

  # POST /actividad_instructors
  # POST /actividad_instructors.json
  def create
    @actividad_instructor = ActividadInstructor.new(actividad_instructor_params)

    respond_to do |format|
      if @actividad_instructor.save
        format.html { redirect_to @actividad_instructor, notice: 'Actividad instructor was successfully created.' }
        format.json { render :show, status: :created, location: @actividad_instructor }
      else
        format.html { render :new }
        format.json { render json: @actividad_instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividad_instructors/1
  # PATCH/PUT /actividad_instructors/1.json
  def update
    respond_to do |format|
      if @actividad_instructor.update(actividad_instructor_params)
        format.html { redirect_to @actividad_instructor, notice: 'Actividad instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad_instructor }
      else
        format.html { render :edit }
        format.json { render json: @actividad_instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividad_instructors/1
  # DELETE /actividad_instructors/1.json
  def destroy
    @actividad_instructor.destroy
    respond_to do |format|
      format.html { redirect_to actividad_instructors_url, notice: 'Actividad instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad_instructor
      @actividad_instructor = ActividadInstructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_instructor_params
      params.require(:actividad_instructor).permit(:actividadExtra_id, :instructor_id, :horario, :lugar)
    end
end

app/controllers/clases_controller.rb
class ClasesController < ApplicationController
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.all

    @profesor_actual = ""
    @materia_actual = ""
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'Clase was successfully created.' }
        format.json { render :show, status: :created, location: @clase }
      else
        format.html { render :new }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'Clase was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase }
      else
        format.html { render :edit }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'Clase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:clave, :materium_id, :profesor_id, :indice, :horario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/actividad_instructors_helper.rb
module ActividadInstructorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clase_alumnos_helper.rb
module ClaseAlumnosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/pgallery_helper.rb
module PgalleryHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/actividad_instructors/_form.html.erb
<%= form_with(model: actividad_instructor, local: true) do |form| %>
  <% if actividad_instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actividad_instructor.errors.count, "error") %> prohibited this actividad_instructor from being saved:</h2>

      <ul>
      <% actividad_instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :actividadExtra_id %>
    <%= form.text_field :actividadExtra_id, id: :actividad_instructor_actividadExtra_id %>
  </div>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.text_field :instructor_id, id: :actividad_instructor_instructor_id %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_field :horario, id: :actividad_instructor_horario %>
  </div>

  <div class="field">
    <%= form.label :lugar %>
    <%= form.text_field :lugar, id: :actividad_instructor_lugar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actividad_instructors/edit.html.erb
<h1>Editing Actividad Instructor</h1>

<%= render 'form', actividad_instructor: @actividad_instructor %>

<%= link_to 'Show', @actividad_instructor %> |
<%= link_to 'Back', actividad_instructors_path %>

app/views/actividad_instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actividad Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Actividadextra</th>
      <th>Instructor</th>
      <th>Horario</th>
      <th>Lugar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividad_instructors.each do |actividad_instructor| %>
      <tr>
        <td><%= actividad_instructor.actividadExtra %></td>
        <td><%= actividad_instructor.instructor %></td>
        <td><%= actividad_instructor.horario %></td>
        <td><%= actividad_instructor.lugar %></td>
        <td><%= link_to 'Show', actividad_instructor %></td>
        <td><%= link_to 'Edit', edit_actividad_instructor_path(actividad_instructor) %></td>
        <td><%= link_to 'Destroy', actividad_instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actividad Instructor', new_actividad_instructor_path %>

app/views/actividad_instructors/new.html.erb
<h1>New Actividad Instructor</h1>

<%= render 'form', actividad_instructor: @actividad_instructor %>

<%= link_to 'Back', actividad_instructors_path %>

app/views/actividad_instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actividadextra:</strong>
  <%= @actividad_instructor.actividadExtra %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @actividad_instructor.instructor %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @actividad_instructor.horario %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @actividad_instructor.lugar %>
</p>

<%= link_to 'Edit', edit_actividad_instructor_path(@actividad_instructor) %> |
<%= link_to 'Back', actividad_instructors_path %>